// <auto-generated />
using System;
using BarometerService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarometerService.Migrations
{
    [DbContext(typeof(BarometerContext))]
    [Migration("20250307101725_AddedIndexForRegisterd")]
    partial class AddedIndexForRegisterd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarometerService.Domain.Model.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altitude")
                        .HasColumnType("double");

                    b.Property<string>("HostName")
                        .HasColumnType("longtext");

                    b.Property<double>("Humidity")
                        .HasColumnType("double");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<double>("Pressure")
                        .HasColumnType("double");

                    b.Property<double>("RefHumidity")
                        .HasColumnType("double");

                    b.Property<double>("RefPressure")
                        .HasColumnType("double");

                    b.Property<double>("RefTemperature")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset>("Registered")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("Registered");

                    b.ToTable("Measures", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
